# Generated by Django 3.2.7 on 2021-10-16 19:31

import cv.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Detail Categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('date_start', models.DateField()),
                ('date_start_display_resolution', models.CharField(choices=[('%Y', 'Year'), ('%Y-%m', 'Month'), ('%M-%m-%d', 'Day')], default='%M-%m-%d', max_length=8)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('date_end_display_resolution', models.CharField(choices=[('%Y', 'Year'), ('%Y-%m', 'Month'), ('%M-%m-%d', 'Day')], default='%M-%m-%d', max_length=8)),
                ('employment_status', models.CharField(blank=True, choices=[('', 'Normal'), ('Internship', 'Internship'), ('Freelancer', 'Freelancer'), ('Self employed', 'Self Employed'), ('Summer job', 'Summer job')], default='', max_length=16)),
                ('visible', models.BooleanField(default=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='cv.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Hobbies',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Personal Info',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(max_length=255, upload_to=cv.models.upload_obfuscated_filename)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='cv.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('number', models.CharField(max_length=32)),
                ('fa_class', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='cv.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='HobbyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobby_items', to='cv.hobby')),
            ],
        ),
        migrations.AddField(
            model_name='hobby',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='cv.personalinfo'),
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('fa_class', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_index', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='cv.personalinfo')),
            ],
            options={
                'ordering': ['sort_index'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_tasks', to='cv.employment')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employers', to='cv.personalinfo'),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('address', models.EmailField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='cv.personalinfo')),
            ],
            options={
                'ordering': ['-primary', 'address'],
            },
        ),
        migrations.CreateModel(
            name='DetailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('detail_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_items', to='cv.detailcategory')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='detailcategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_categories', to='cv.personalinfo'),
        ),
    ]
