version: '3'

services:
  app:
    container_name: cv_backend
    env_file:
      - .env
    build: backend
    # command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:${DJANGO_PORT}"
    # command: sh -c "python manage.py runserver 0.0.0.0:${DJANGO_PORT}"
    # command: sh -c "gunicorn config.wsgi --workers ${UWSGI_WORKERS} --graceful-timeout 3600 --timeout 3600 --bind 0.0.0.0:${DJANGO_PORT}"
    volumes:
      - ./backend:/app/
    ports:
      - "127.0.0.1:${DJANGO_PORT}:${DJANGO_PORT}"
    restart: unless-stopped


  web:
    container_name: cv_frontend
    build: frontend
    # command: sh -c "npm start"
    volumes:
      - ./frontend:/app/
    ports:
      - "127.0.0.1:${REACT_PORT}:${REACT_PORT}"
