# Generated by Django 5.1.5 on 2025-01-23 18:32

import cv.models
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='tag')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioTechniques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('url_type', models.CharField(blank=True, choices=[('', 'None'), ('Live', 'Live'), ('Demo', 'Demo')], default='', max_length=16, null=True)),
                ('repository', models.URLField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='cv.personalinfo')),
                ('tags', models.ManyToManyField(blank=True, related_name='items', to='cv.portfolioitemtag')),
                ('techniques', models.ManyToManyField(blank=True, related_name='items', to='cv.portfoliotechniques')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Primary', 'Primary'), ('Desktop', 'Desktop'), ('Mobile', 'Mobile')], default='Primary', max_length=16)),
                ('image', models.ImageField(upload_to=cv.models.upload_obfuscated_filename)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=cv.models.upload_obfuscated_filename)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cv.portfolioitem')),
            ],
        ),
    ]
