# Generated by Django 5.1.5 on 2025-01-24 14:25

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_portfolioitemtag_portfoliotechniques_portfolioitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
