# Generated by Django 5.1.5 on 2025-01-24 14:29

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_portfolioitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='portfolioitemtag',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from='tag'),
        ),
    ]
