# Generated by Django 2.1.1 on 2018-09-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20180919_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalphonenumber',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Home'), (1, 'Work'), (2, 'Mobile'), (3, 'Fax'), (4, 'Beeper'), (5, 'Other')]),
        ),
    ]
