# Generated by Django 2.1.1 on 2018-09-19 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20180919_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalphonenumber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_phone_numbers', to='info.PersonalInfo'),
        ),
    ]
