# Generated by Django 2.1.1 on 2018-09-19 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20180919_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('type', models.SmallIntegerField(choices=[(0, 'Mobile'), (1, 'Work'), (2, 'Home'), (3, 'Fax'), (4, 'Beeper'), (5, 'Other')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_phone_numbers', to='info.PersonalInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='personalphonenumber',
            name='user',
        ),
        migrations.DeleteModel(
            name='PersonalPhoneNumber',
        ),
    ]
