# Generated by Django 2.1.2 on 2018-10-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20180919_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallink',
            name='url_type',
            field=models.CharField(choices=[('external-link', 'Other'), ('soundcloud', 'Soundcloud'), ('linkedin-square', 'LinkedIn')], default='external-link', max_length=16),
        ),
    ]
