# Generated by Django 2.1.2 on 2018-10-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_externallink_url_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('work', 'Work'), ('home', 'Home'), ('fax', 'Fax'), ('beeper', 'Beeper'), ('other', 'Other')], default='mobile', max_length=8),
        ),
    ]
