# Generated by Django 2.1.2 on 2018-10-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_auto_20181028_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='type',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Work', 'Work'), ('Home', 'Home'), ('Fax', 'Fax'), ('Beeper', 'Beeper'), ('Other', 'Other')], default='Mobile', max_length=8),
        ),
    ]
