# Generated by Django 2.1.2 on 2018-10-27 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='HobbyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbyitems', to='hobby.Hobby')),
            ],
        ),
    ]
