# Generated by Django 2.1.2 on 2018-10-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hobbyitem',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
