# Generated by Django 2.1.2 on 2018-10-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0002_auto_20181027_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='description',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
