# Generated by Django 2.1.2 on 2018-10-28 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0003_auto_20181027_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbyitem',
            name='hobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hobby.Hobby'),
        ),
    ]
