# Generated by Django 2.1.1 on 2018-09-19 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalLink',
        ),
        migrations.RemoveField(
            model_name='personalemail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='personalphonenumber',
            name='user',
        ),
        migrations.DeleteModel(
            name='PersonalEmail',
        ),
        migrations.DeleteModel(
            name='PersonalInfo',
        ),
        migrations.DeleteModel(
            name='PersonalPhoneNumber',
        ),
    ]
