# Generated by Django 2.1.1 on 2018-09-21 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20180919_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='cv.Employer'),
        ),
        migrations.AlterField(
            model_name='employmenttask',
            name='employment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_tasks', to='cv.Employment'),
        ),
    ]
