# Generated by Django 2.1.1 on 2018-09-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20180921_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='date_end_display_resolution',
            field=models.CharField(choices=[('Year', '%Y'), ('Month', '%Y-%m'), ('Day', '%d')], default=('Day', '%d'), max_length=8),
        ),
        migrations.AddField(
            model_name='employment',
            name='date_start_display_resolution',
            field=models.CharField(choices=[('Year', '%Y'), ('Month', '%Y-%m'), ('Day', '%d')], default=('Day', '%d'), max_length=8),
        ),
    ]
