# Generated by Django 2.1.1 on 2018-09-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20180924_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='date_end_display_resolution',
            field=models.CharField(choices=[('%Y', 'Year'), ('%Y-%m', 'Month'), ('%M-%m-%d', 'Day')], default='Day', max_length=8),
        ),
        migrations.AlterField(
            model_name='employment',
            name='date_start_display_resolution',
            field=models.CharField(choices=[('%Y', 'Year'), ('%Y-%m', 'Month'), ('%M-%m-%d', 'Day')], default='Day', max_length=8),
        ),
    ]
