# Generated by Django 2.1.1 on 2018-09-24 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20180924_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmenttask',
            name='visible',
        ),
    ]
