# Generated by Django 2.1.2 on 2018-10-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_remove_employmenttask_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='internship',
        ),
        migrations.AlterField(
            model_name='employment',
            name='date_end_display_resolution',
            field=models.CharField(choices=[('%Y', 'Year'), ('%Y-%m', 'Month'), ('%M-%m-%d', 'Day')], default='%M-%m-%d', max_length=8),
        ),
        migrations.AlterField(
            model_name='employment',
            name='date_start_display_resolution',
            field=models.CharField(choices=[('%Y', 'Year'), ('%Y-%m', 'Month'), ('%M-%m-%d', 'Day')], default='%M-%m-%d', max_length=8),
        ),
    ]
