# Generated by Django 2.1.2 on 2018-10-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_auto_20181027_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='employment_status',
            field=models.PositiveIntegerField(choices=[(0, 'Normal'), (1, 'Internship'), (2, 'Freelancer'), (3, 'Self Employed')], default=0),
        ),
    ]
