# Generated by Django 2.1.2 on 2018-10-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_employment_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='employment_status',
            field=models.PositiveIntegerField(choices=[('', 'Normal'), ('Internship', 'Internship'), ('Freelancer', 'Freelancer'), ('Self employed', 'Self Employed')], default=0),
        ),
    ]
