# Generated by Django 2.1.2 on 2018-10-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_auto_20181027_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='employment_status',
            field=models.CharField(choices=[('', 'Normal'), ('Internship', 'Internship'), ('Freelancer', 'Freelancer'), ('Self employed', 'Self Employed')], default=0, max_length=16),
        ),
    ]
