# Generated by Django 2.1.2 on 2018-10-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_auto_20181027_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='employment_status',
        ),
    ]
