# Generated by Django 2.1.2 on 2018-10-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_remove_employment_employment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='employment_status',
            field=models.CharField(choices=[('', 'Normal'), ('Internship', 'Internship'), ('Freelancer', 'Freelancer'), ('Self employed', 'Self Employed')], default='', max_length=16),
        ),
    ]
