# Generated by Django 2.1.2 on 2018-12-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_employment_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('', 'Normal'), ('Internship', 'Internship'), ('Freelancer', 'Freelancer'), ('Self employed', 'Self Employed')], default='', max_length=16, null=True),
        ),
    ]
